default_language_version:
  python: python3
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.6.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus, --application-directories, "koku"]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.19.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    args: [--line-length, "119"]
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ".unleash/"
  - id: debug-statements
  - id: flake8
- repo: https://github.com/haizaar/check-pipfile-lock
  rev: v0.0.3
  hooks:
    - id: check-pipfile-lock
- repo: local
  hooks:
    - id: validate-dashboards
      name: Validate Grafana Dashboards
      description: Ensures dashboard files are valid JSON
      entry: scripts/validate_dashboards.sh
      language: script
      pass_filenames: false
      files: dashboards\/.*\.yaml
