language: python

python:
  - "3.6"
  - "3.8"

dist: bionic

cache:
  - pip
  - directories:
    - $HOME/.cache/pre-commit/
services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-client-10

env:
  DATABASE_SERVICE_NAME=POSTGRES_SQL
  DATABASE_ENGINE=postgresql
  DATABASE_NAME=koku_test
  POSTGRES_SQL_SERVICE_HOST=localhost
  POSTGRES_SQL_SERVICE_PORT=5432
  DATABASE_USER=postgres
  DATABASE_PASSWORD=''
  TOXENV=for_travis

before_install:
  - sudo rm -f /etc/boto.cfg
  - sudo mount -o remount,size=25% /var/ramfs

install:
  - pip install tox-travis codecov "coverage<5.0" pre-commit

before_script:
  - psql -c "create database ${DATABASE_NAME};" -U postgres

script:
  - .travis/check_manifest.sh
  - pre-commit run --all-files
  - df -h
  - tox
  - df -h


notifications:
  slack:
    secure: azhEHslQ7cxp0RVhnHBf6PygTldO/B03CAuG1vBOhklNAtJvt2WUF1xtoxyfmb4FDb5R+Qa2piypMiLxmvuZPZY2DTDIv/bAIwiItG78SrEkXEkaqc46YmgX7yPhSeK+5wTO9rqXqEOOgZ+f43RaIFDEp8M/S1sPe8ROEfvYTJ01v7XyurhxV1Jzawk9fNL7tcbrkbe3bXo+4+yiqWBGQ5B/E8AOlHlxGhWFh401p4fEzYecPU6UHRucbYswDmkVxr84GT/j5dbi/GXwr9FxRVGv3Lm9CLaSI0MbgaNBKnUhgO+SN40AxYGUcGwqEB5352rYmlsJXF44HBMkW22ZECceCJbc4dS6dX9MHh2dxc5iFfKFR9cAwPb6BiY+efDvUfN83MWGeTe6BFvKB8BItSVVck96Vq/1WAgxUgU2oiwKA53+pcjJW/H/TgviKwvSqLhq643aGX7zZys6Nm6jwKIn33jclxUkNTo3W4svN43nV4GF9G+klwa9HxZzI2y32JYzrIf/L9ihCS00TlWZP/1jf3xjr5il2vfezAtDVJ+dx4hmX+VIfRGDFCTs5lfER/OtlpsvFFJraSy+rMHKc57HDz9tKPzCNtSmYweof2HU/QdXt2/Fbd7eGQNJxaJ3m8GxPi6FyNVu1VkbH4TIj6HlltGfB9TJBS9lU5Fs0nQ=
