# The Makefile will automatically use this file on ARM systems

version: '3'

services:
  hive-metastore:
    image: quay.io/mskarbek/ubi-hive:3.1.3-metastore-024

  trino:
    image: quay.io/mskarbek/ubi-trino:427-001
