version: '3'

services:
  koku-minio:
    image: minio/minio:latest
    container_name: kokuminio
    environment:
      MINIO_ACCESS_KEY: kokuminioaccess
      MINIO_SECRET_KEY: kokuminiosecret
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - ./../../testing/parquet_data:/data

  koku-create-parquet-bucket:
    image: minio/mc:latest
    depends_on:
      - koku-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://kokuminio:9000 kokuminioaccess kokuminiosecret;
      /usr/bin/mc rb --force local/koku-bucket/;
      /usr/bin/mc mb --quiet local/koku-bucket/;
      /usr/bin/mc policy set public local/koku-bucket;
      /usr/bin/mc rb --force local/metastore/;
      /usr/bin/mc mb --quiet local/metastore/;
      /usr/bin/mc policy set public local/metastore;

      "

  hive-metastore:
    container_name: hive-metastore
    image: quay.io/cloudservices/ubi-hive:2.3.3-002
    entrypoint:  ["/hive-scripts/entrypoint.sh", "/opt/hive/bin/hive", "--service", "metastore"]
    ports:
      - "9083:9083"
    environment:
      - HIVE_LOGLEVEL=INFO
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET}
    volumes:
      - ./../../testing/metastore/hive-config:/hive-config
      - ./../../testing/metastore/hive-scripts:/hive-scripts
      - ./../../testing/metastore/hive-jmx-config:/opt/jmx_exporter/config
      - ./../../testing/metastore/db-data:/var/lib/hive
      - ./../../testing/hadoop/hadoop-dfs-name:/hadoop/dfs/name
      - ./../../testing/hadoop/hadoop-dfs-data:/hadoop/dfs/data
      - ./../../testing/hadoop/hadoop-logs:/opt/hadoop/logs
      - ./../../testing/hadoop/hadoop-config:/hadoop-config
      - ./../../testing/hadoop/hadoop-starting-config:/hadoop-starting-config

  presto:
    container_name: presto
    image: quay.io/cloudservices/ubi-trino:348-001
    user: root
    # If using trino (presto) release >= 351,
    # change "presto" to "trino" here and below in this stanza
    command: /presto-common/initialize_presto.sh
    ports:
      - "8080:8080"
    environment:
      - MY_NODE_ID=${MY_NODE_ID-localhost}
      - LOCAL=TRUE
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET}
      - S3_ENDPOINT=${S3_ENDPOINT}
    volumes:
      - ./../../testing/presto/presto-common-config:/presto-common
      - ./../../testing/presto/presto-coordinator-config/:/presto-etc
      - ./../../testing/presto/presto-catalog-config:/presto-etc/catalog
      - ./../../testing/presto/presto-etc:/opt/presto/presto-server/etc
      - ./../../testing/presto/presto-jmx-config:/opt/jmx_exporter/config
      - ./../../testing/presto/presto-data:/var/presto/data
      - ./../../testing/presto/presto-logs:/var/presto/logs
      - ./../../testing/hadoop/hadoop-config:/hadoop-config
      - ./../../testing/hadoop/hadoop-starting-config:/hadoop-starting-config
    links:
      - hive-metastore
    depends_on:
      - hive-metastore

networks:
 default:
   external:
     name: koku_default
