- op: add
  path: /objects/0/spec/deployments/-
  value:
    name: clowder-worker-cost-model-xl
    metadata:
      annotations:
        ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses 1 pod at times for cost saving purposes
    webServices:
      public:
        enabled: false
      private:
        enabled: false
    podSpec:
      metadata:
        annotations:
          ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses 1 pod at times for cost saving purposes
      image: ${IMAGE}:${IMAGE_TAG}
      command:
        - /bin/bash
        - -c
        - > # ${APP_HOME} is `/opt/koku/koku` which is defined in the Dockerfile
          PYTHONPATH=${APP_HOME}
          celery -A koku worker --without-gossip -E -l $CELERY_LOG_LEVEL -Q $WORKER_QUEUES
      env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: REDEPLOY_HASH
          value: ${REDEPLOY_HASH_ALL}_${REDEPLOY_HASH_WORKER_COST_MODEL_XL}
        - name: SCHEMA_SUFFIX
          value: ${SCHEMA_SUFFIX}
        - name: TRINO_S3A_OR_S3
          value: ${TRINO_S3A_OR_S3}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: koku-aws
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: koku-aws
              optional: false
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ${GOOGLE_APPLICATION_CREDENTIALS}
        - name: APP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SOURCES_PSK
          valueFrom:
            secretKeyRef:
              key: psk
              name: ${SOURCES_PSK_SECRET_NAME}
              optional: true
        - name: DEVELOPMENT
          value: ${DEVELOPMENT}
        - name: ONPREM
          value: ${ONPREM}
        - name: CELERY_LOG_LEVEL
          value: ${CELERY_LOG_LEVEL}
        - name: KOKU_LOG_LEVEL
          value: ${KOKU_LOG_LEVEL}
        - name: UNLEASH_LOG_LEVEL
          value: ${UNLEASH_LOG_LEVEL}
        - name: PROMETHEUS_MULTIPROC_DIR
          value: ${PROMETHEUS_DIR}
        - name: REQUESTED_BUCKET
          value: ${S3_BUCKET_NAME}
        - name: PARQUET_PROCESSING_BATCH_SIZE
          value: ${PARQUET_PROCESSING_BATCH_SIZE}
        - name: TRINO_DATE_STEP
          value: ${TRINO_DATE_STEP}
        - name: VALIDATION_RANGE
          value: ${VALIDATION_RANGE}
        - name: KOKU_ENABLE_SENTRY
          value: ${KOKU_ENABLE_SENTRY}
        - name: KOKU_SENTRY_ENVIRONMENT
          value: ${KOKU_SENTRY_ENV}
        - name: KOKU_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: ${GLITCHTIP_KEY_NAME}
              name: ${GLITCHTIP_SECRET_NAME}
              optional: true
        - name: DEMO_ACCOUNTS
          value: ${DEMO_ACCOUNTS}
        - name: WORKER_QUEUES
          value: ${WORKER_COST_MODEL_XL_WORKER_QUEUE}
        - name: WORKER_PROC_ALIVE_TIMEOUT
          value: ${WORKER_PROC_ALIVE_TIMEOUT}
        - name: DATE_OVERRIDE
          value: ${DATE_OVERRIDE}
        - name: RETAIN_NUM_MONTHS
          value: ${RETAIN_NUM_MONTHS}
        - name: INITIAL_INGEST_NUM_MONTHS
          value: ${INITIAL_INGEST_NUM_MONTHS}
        - name: INITIAL_INGEST_OVERRIDE
          value: ${INITIAL_INGEST_OVERRIDE}
        - name: POLLING_TIMER
          value: ${POLLING_TIMER}
        - name: POLLING_COUNT
          value: ${POLLING_COUNT}
        - name: XL_REPORT_COUNT
          value: ${XL_REPORT_COUNT}
        - name: PROCESSING_WAIT_TIMER
          value: ${PROCESSING_WAIT_TIMER}
        - name: LARGE_PROCESSING_WAIT_TIMER
          value: ${LARGE_PROCESSING_WAIT_TIMER}
        - name: TRINO_HOST
          value: ${TRINO_HOST}
        - name: TRINO_PORT
          value: ${TRINO_PORT}
        - name: AUTO_DATA_INGEST
          value: ${AUTO_DATA_INGEST}
        - name: REPORT_PROCESSING_BATCH_SIZE
          value: ${REPORT_PROCESSING_BATCH_SIZE}
        - name: PROMETHEUS_PUSHGATEWAY
          value: ${PROMETHEUS_PUSHGATEWAY}
        - name: SOURCES_API_PREFIX
          value: ${SOURCES_API_PREFIX}
        - name: UNLEASH_CACHE_DIR
          value: ${UNLEASH_CACHE_DIR}
        - name: WORKER_CACHE_TIMEOUT
          value: ${WORKER_CACHE_TIMEOUT}
        - name: WORKER_CACHE_LARGE_CUSTOMER_TIMEOUT
          value: ${WORKER_CACHE_LARGE_CUSTOMER_TIMEOUT}
        - name: WORKER_CACHE_LARGE_CUSTOMER_CONCURRENT_TASKS
          value: ${WORKER_CACHE_LARGE_CUSTOMER_CONCURRENT_TASKS}
        - name: QE_SCHEMA
          value: ${QE_SCHEMA}
        - name: ENHANCED_ORG_ADMIN
          value: ${ENHANCED_ORG_ADMIN}
      livenessProbe:
        httpGet:
          path: /livez
          port: metrics
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 5
        timeoutSeconds: 10
      readinessProbe:
        httpGet:
          path: /readyz
          port: metrics
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 5
        timeoutSeconds: 10
      terminationGracePeriodSeconds: 3600
      resources:
        limits:
          cpu: ${CPU_LIMIT_WORKER_COST_MODEL_XL}
          memory: ${MEMORY_LIMIT_WORKER_COST_MODEL_XL}
        requests:
          cpu: ${CPU_REQUEST_WORKER_COST_MODEL_XL}
          memory: ${MEMORY_REQUEST_WORKER_COST_MODEL_XL}
      volumeMounts:
      - mountPath: /var/tmp/masu/
        name: koku-worker-data
      - name: gcp-credentials
        mountPath: /etc/gcp
        readOnly: true
      - name: tmp-data
        mountPath: ${TMP_DIR}
      volumes:
      - name: tmp-data
        emptyDir: {}
      - name: koku-worker-data
        emptyDir: {}
      - name: gcp-credentials
        secret:
          secretName: koku-gcp
          items:
            - key: gcp-credentials
              path: gcp-credentials.json
    autoScaler:
      maxReplicaCount: ${{WORKER_COST_MODEL_XL_MAX_REPLICAS}}
      minReplicaCount: ${{WORKER_COST_MODEL_XL_MIN_REPLICAS}}
      fallback:
        failureThreshold: 3
        replicas: ${{WORKER_COST_MODEL_XL_FALLBACK_REPLICAS}}
        behavior: "currentReplicasIfHigher"
      triggers:
      - type: prometheus
        metadata:
          query: ${WORKER_COST_MODEL_XL_TRIGGER_QUERY}
          threshold: ${WORKER_COST_MODEL_XL_TRIGGER_THRESHOLD}
- op: add
  path: /parameters/-
  value:
    displayName: Minimum replicas
    name: WORKER_COST_MODEL_XL_MIN_REPLICAS
    required: true
    value: '1'
- op: add
  path: /parameters/-
  value:
    displayName: Maximum replicas
    name: WORKER_COST_MODEL_XL_MAX_REPLICAS
    required: true
    value: '10'
- op: add
  path: /parameters/-
  value:
    displayName: Fallback replicas
    name: WORKER_COST_MODEL_XL_FALLBACK_REPLICAS
    required: true
    value: '3'
- op: add
  path: /parameters/-
  value:
    displayName: Trigger threshold
    name: WORKER_COST_MODEL_XL_TRIGGER_THRESHOLD
    required: true
    value: '13.5'
- op: add
  path: /parameters/-
  value:
    displayName: Trigger query
    name: WORKER_COST_MODEL_XL_TRIGGER_QUERY
    required: true
    value: 'koku:celery:cost_model_xl_queue'
- op: add
  path: /parameters/-
  value:
    displayName: Memory Request
    name: MEMORY_REQUEST_WORKER_COST_MODEL_XL
    required: true
    value: 256Mi
- op: add
  path: /parameters/-
  value:
    displayName: Memory Limit
    name: MEMORY_LIMIT_WORKER_COST_MODEL_XL
    required: true
    value: 512Mi
- op: add
  path: /parameters/-
  value:
    displayName: CPU Request
    name: CPU_REQUEST_WORKER_COST_MODEL_XL
    required: true
    value: 100m
- op: add
  path: /parameters/-
  value:
    displayName: CPU Limit
    name: CPU_LIMIT_WORKER_COST_MODEL_XL
    required: true
    value: 200m
- op: add
  path: /parameters/-
  value:
    displayName: Worker Queue
    name: WORKER_COST_MODEL_XL_WORKER_QUEUE
    required: true
    value: 'cost_model_xl'
- op: add
  path: /parameters/-
  value:
    description: change this value to restart worker-cost-model-xl
    name: REDEPLOY_HASH_WORKER_COST_MODEL_XL
    value: "000000"
- op: add
  path: /parameters/-
  value:
    description: toggles on-prem data processing flow
    name: ONPREM
    required: true
    value: "False"
