name: Send Release Notificaion

on:
  release:
    types:
    - released
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release Notifier Action
      uses: bitoiu/release-notify-action@v1.0
      env:
        SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
